[workspace]
authors = ["iz4ack <luciaisaac.nv@gmail.com>"]
channels = ["conda-forge"]
name = "rdb2owl"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
graph-tool = ">=2.97,<3"
python = ">=3.12.10,<3.13"
pytorch = ">=2.6.0,<3"
absl-py = ">=2.2.0,<3"
jinja2 = ">=3.1.6,<4"
matplotlib = ">=3.10.1,<4"
networkx = ">=3.4.2,<4"
numpy = ">=2.2.5,<3"
rdflib = ">=7.1.4,<8"
scikit-learn = ">=1.6.1,<2"
scipy = ">=1.15.2,<2"
scienceplots = ">=2.1.1,<3"
sentence-transformers = ">=4.1.0,<5"
torch-geometric = ">=2.6.1,<3"
tqdm = ">=4.67.1,<5"
wandb = ">=0.19.10,<0.20"
transformers = ">=4.51.3,<5"
cairo = ">=1.18.4,<2"
cairomm = ">=1.16.2,<2"
pygobject = ">=3.50.0,<4"
pyyaml = ">=6.0.2,<7"
huggingface_hub = ">=0.30.2,<0.31"
